update RDB$FIELDS set
RDB$FIELD_LENGTH = 30,
RDB$CHARACTER_LENGTH = 30
where RDB$FIELD_NAME = 'RDB$40'
;

update RDB$FIELDS set
RDB$FIELD_TYPE = 16,
RDB$FIELD_LENGTH = 8,
RDB$CHARACTER_LENGTH = NULL,
RDB$FIELD_SCALE = -2,
RDB$FIELD_PRECISION = 18
where RDB$FIELD_NAME = 'RDB$129'
;

update RDB$FIELDS set
RDB$FIELD_TYPE = 16,
RDB$FIELD_LENGTH = 8,
RDB$CHARACTER_LENGTH = NULL,
RDB$FIELD_SCALE = -2,
RDB$FIELD_PRECISION = 18
where RDB$FIELD_NAME = 'RDB$131'
;
update RDB$FIELDS set
RDB$FIELD_TYPE = 12
where RDB$FIELD_NAME = 'RDB$133'
;


update RDB$FIELDS set
RDB$FIELD_TYPE = 16,
RDB$FIELD_LENGTH = 8,
RDB$CHARACTER_LENGTH = NULL,
RDB$FIELD_SCALE = -2,
RDB$FIELD_PRECISION = 18
where RDB$FIELD_NAME = 'RDB$132'
;



ALTER TABLE RESERVA
ADD DATA_DEVOLUCAO DOM_DATA1;

